[build]
  command = "npm run build"
  publish = ".next"

[template]
  incoming-hooks = ["WixEvents"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_WIX_CLIENT_ID = "Wix Headless Client ID"
  WIX_REFRESH_TOKEN = "A refresh token for admin access"
